# Generated by Django 4.2.1 on 2023-05-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ids',
            new_name='Unique',
        ),
    ]
